image: alpine

stages:
    - genARD

genARD:
    stage: genARD
    before_script:
        - mkdir -p ~/.ssh
        - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - apk update && apk add python3 py3-pip texlive-full openssh-client doxygen alpine-sdk linux-headers boost-dev
        - pip3 install sphinx sphinx-rtd-theme
    script:
        - make
        - ssh deployuser@elon.sdsurocketproject.org "rm -f /var/www/html/wikistatic/Helix-Software/ARD/ARD.pdf"
        - scp ARD/ARD.pdf deployuser@elon.sdsurocketproject.org:/var/www/html/wikistatic/Helix-Software/ARD/ARD.pdf
    only:
        - master
