image: alpine

stages:
    - compileARD
    - genARD

compileARD:
    stage: compileARD
    before_script:
        - apk update && apk add python3 py3-pip texlive-full openssh-client alpine-sdk
        - pip3 install sphinx sphinx-rtd-theme
    script:
        - make

genARD:
    stage: genARD
    before_script:
        - mkdir -p ~/.ssh
        - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - apk update && apk add python3 py3-pip texlive-full openssh-client alpine-sdk rsync
        - pip3 install sphinx sphinx-rtd-theme
    script:
        - make
        - ssh deployuser@elon.sdsurocketproject.org "rm -f /var/www/html/wikistatic/Helix-Software/ARD/ARD.pdf"
        - scp ARD.pdf deployuser@elon.sdsurocketproject.org:/var/www/html/wikistatic/Helix-Software/ARD/ARD.pdf
        - rsync -avP --delete docs/build/html/ deployuser@elon.sdsurocketproject.org:/var/www/html/wikistatic/Helix-Software-Documentation/ARD/
    only:
        - master
