// WARNING START OF SECTION AUTOGENERATED BY PYTHON SCRIPT
// THIS SECTION MAY BE AUTOMATICALLY CHANGED AT ANY TIME
// Autogenerated section name: CAN Config
// File path of script: ARD/genCAN.py
#ifndef CANIDS_H_
#define CANIDS_H_

#include <linux/can.h>
#include <stdint.h>

enum STATES {
	STATE_IDLE,
	STATE_DEBUG,
	STATE_DRY_SYSTEMS,
	STATE_LEAK_CHECK,
	STATE_FUELING,
	STATE_LAUNCH,
	STATE_STAGE_TWO,
	STATE_RECOVERY,
	STATE_GROUND_SAFE,
	STATE_FLIGHT_SAFE,
	STATE_MAX_STATES
};

enum CANIDs : uint32_t {
	CANIDS_PRIMARY_CLOCK_SYNC = 0UL,
	CANIDS_OBC_CLOCK_SYNC = 1UL,
	CANIDS_EMERGENCY_SIGNAL = 10UL,
	CANIDS_TRANSITION_CONE_STATUS = 50UL,
	CANIDS_ARM_RECOVERY = 60UL,
	CANIDS_DETATCH_SECOND_STAGE = 61UL,
	CANIDS_HELIUM_PRESSURE_PT_DATA = 100UL,
	CANIDS_LOX_PRESSURE_PT_DATA = 101UL,
	CANIDS_ETHANOL_PRESSURE_PT_DATA = 102UL,
	CANIDS_CHAMBER_PRESSURE_PT_DATA = 103UL,
	CANIDS_HELIUM_FILL_VALVE_HALL_EFFECT_STATE = 200UL,
	CANIDS_LOX_FILL_VALVE_HALL_EFFECT_STATE = 201UL,
	CANIDS_ETHANOL_FILL_VALVE_HALL_EFFECT_STATE = 202UL,
	CANIDS_LOX_TANK_LIQUID_LEVEL_DATA = 250UL,
	CANIDS_ETHANOL_TANK_LIQUID_LEVEL_DATA = 251UL,
	CANIDS_LOX_TANK_TEMPERATURE_DATA = 300UL,
	CANIDS_ETHANOL_TANK_TEMPERATURE_DATA = 301UL,
	CANIDS_NOZZLE_TEMPERATURE_DATA = 302UL,
	CANIDS_UPPER_AIR_FRAME_TEMPERATURE_DATA = 303UL,
	CANIDS_ITC_TEMPERATURE_DATA = 304UL,
	CANIDS_LOWER_AIR_FRAME_TEMPERATURE_DATA = 305UL,
	CANIDS_HELIUM_PRESSURE_PT_CURRENT = 400UL,
	CANIDS_LOX_PRESSURE_PT_CURRENT = 401UL,
	CANIDS_ETHANOL_PRESSURE_PT_CURRENT = 402UL,
	CANIDS_CHAMBER_PRESSURE_PT_CURRENT = 403UL,
	CANIDS_HELIUM_FILL_VALVE_HALL_EFFECT_CURRENT = 404UL,
	CANIDS_LOX_FILL_VALVE_HALL_EFFECT_CURRENT = 405UL,
	CANIDS_ETHANOL_FILL_VALVE_HALL_EFFECT_CURRENT = 406UL,
	CANIDS_UPPER_AIR_FRAME_VIN_CURRENT = 407UL,
	CANIDS_ITC_VIN_CURRENT = 408UL,
	CANIDS_LOWER_AIR_FRAME_VIN_CURRENT = 409UL,
	CANIDS_UPPER_AIR_FRAME_VIN_VOLTAGE = 500UL,
	CANIDS_ITC_VIN_VOLTAGE = 501UL,
	CANIDS_LOWER_AIR_FRAME_VIN_VOLTAGE = 502UL,
	CANIDS_MAX_CANID
};

struct primaryClockSync {
	uint32_t timeSinceSystemStart;
};

struct obcClockSync {
	uint32_t timeSinceSystemStart;
};

struct emergencySignal {
	uint8_t status;
};

struct transitionConeStatus {
	uint8_t status;
};

struct armRecovery {
	uint8_t status;
};

struct detatchSecondStage {
	uint8_t status;
};

struct heliumPressurePtData {
	uint32_t timeSinceSystemStart;
	uint16_t heliumPressure;
	uint16_t rawHeliumPressureMeasurement;
};

struct loxPressurePtData {
	uint32_t timeSinceSystemStart;
	uint16_t loxPressure;
	uint16_t rawLoxPressureMeasurement;
};

struct ethanolPressurePtData {
	uint32_t timeSinceSystemStart;
	uint16_t ethanolPressure;
	uint16_t rawEthanolPressureMeasurement;
};

struct chamberPressurePtData {
	uint32_t timeSinceSystemStart;
	uint16_t chamberPressure;
	uint16_t rawChamberPressureMeasurement;
};

struct heliumFillValveHallEffectState {
	uint32_t timeSinceSystemStart;
	uint8_t heliumFillValveHallEffectState;
};

struct loxFillValveHallEffectState {
	uint32_t timeSinceSystemStart;
	uint8_t loxFillValveHallEffectState;
};

struct ethanolFillValveHallEffectState {
	uint32_t timeSinceSystemStart;
	uint8_t ethanolFillValveHallEffectState;
};

struct loxTankLiquidLevelData {
	uint32_t timeSinceSystemStart;
	uint8_t loxTankLiquidLevel;
	uint16_t rawLoxTankLiquidLevelMeasurement;
};

struct ethanolTankLiquidLevelData {
	uint32_t timeSinceSystemStart;
	uint8_t ethanolTankLiquidLevel;
	uint16_t rawEthanolTankLiquidLevelMeasurement;
};

struct loxTankTemperatureData {
	uint32_t timeSinceSystemStart;
	int16_t loxTankTemperature;
	uint16_t rawLoxTankTemperatureMeasurement;
};

struct ethanolTankTemperatureData {
	uint32_t timeSinceSystemStart;
	int16_t ethanolTankTemperature;
	uint16_t rawEthanolTankTemperatureMeasurement;
};

struct nozzleTemperatureData {
	uint32_t timeSinceSystemStart;
	int16_t nozzleTemperature;
	uint16_t rawNozzleTemperatureMeasurement;
};

struct upperAirFrameTemperatureData {
	uint32_t timeSinceSystemStart;
	int16_t upperAirFrameTemperature;
	uint16_t rawUpperAirFrameTemperatureMeasurement;
};

struct itcTemperatureData {
	uint32_t timeSinceSystemStart;
	int16_t itcTemperature;
	uint16_t rawItcTemperatureMeasurement;
};

struct lowerAirFrameTemperatureData {
	uint32_t timeSinceSystemStart;
	int16_t lowerAirFrameTemperature;
	uint16_t rawLowerAirFrameTemperatureMeasurement;
};

struct heliumPressurePtCurrent {
	uint32_t timeSinceSystemStart;
	int16_t heliumPressurePtCurrent;
	uint16_t rawHeliumPressurePtCurrentMeasurement;
};

struct loxPressurePtCurrent {
	uint32_t timeSinceSystemStart;
	int16_t loxPressurePtCurrent;
	uint16_t rawLoxPressurePtCurrentMeasurement;
};

struct ethanolPressurePtCurrent {
	uint32_t timeSinceSystemStart;
	int16_t ethanolPressurePtCurrent;
	uint16_t rawEthanolPressurePtCurrentMeasurement;
};

struct chamberPressurePtCurrent {
	uint32_t timeSinceSystemStart;
	int16_t chamberPressurePtCurrent;
	uint16_t rawChamberPressurePtCurrentMeasurement;
};

struct heliumFillValveHallEffectCurrent {
	uint32_t timeSinceSystemStart;
	int16_t heliumFillValveHallEffectCurrent;
	uint16_t rawHeliumFillValveHallEffectCurrentMeasurement;
};

struct loxFillValveHallEffectCurrent {
	uint32_t timeSinceSystemStart;
	int16_t loxFillValveHallEffectCurrent;
	uint16_t rawLoxFillValveHallEffectCurrentMeasurement;
};

struct ethanolFillValveHallEffectCurrent {
	uint32_t timeSinceSystemStart;
	int16_t ethanolFillValveHallEffectCurrent;
	uint16_t rawEthanolFillValveHallEffectCurrentMeasurement;
};

struct upperAirFrameVinCurrent {
	uint32_t timeSinceSystemStart;
	int16_t upperAirFrameBoardCurrent;
	uint16_t rawUpperAirFrameBoardCurrentMeasurement;
};

struct itcVinCurrent {
	uint32_t timeSinceSystemStart;
	int16_t itcBoardCurrent;
	uint16_t rawItcBoardCurrentMeasurement;
};

struct lowerAirFrameVinCurrent {
	uint32_t timeSinceSystemStart;
	int16_t lowerAirFrameBoardCurrent;
	uint16_t rawLowerAirFrameBoardCurrentMeasurement;
};

struct upperAirFrameVinVoltage {
	uint32_t timeSinceSystemStart;
	int16_t upperAirFrameBoardVinVoltage;
	uint16_t rawUpperAirFrameBoardVinVoltageMeasurement;
};

struct itcVinVoltage {
	uint32_t timeSinceSystemStart;
	int16_t itcBoardVinVoltage;
	uint16_t rawItcBoardVinVoltageMeasurement;
};

struct lowerAirFrameVinVoltage {
	uint32_t timeSinceSystemStart;
	int16_t lowerAirFrameBoardVinVoltage;
	uint16_t rawLowerAirFrameBoardVinVoltageMeasurement;
};

#endif // CANIDS_H_
// WARNING END OF SECTION AUTOGENERATED BY PYTHON SCRIPT
// THIS SECTION MAY BE AUTOMATICALLY CHANGED AT ANY TIME
// Autogenerated section name: CAN Config
// File path of script: ARD/genCAN.py
