
HEADER = '\033[95m'
OKBLUE = '\033[94m'
OKGREEN = '\033[92m'
WARNING = '\033[93m'
FAIL = '\033[91m'
ENDC = '\033[0m'
BOLD = "\033[1m"

def autogenWarnStart(sectionName, filePath, commentChar="%"):
	out = commentChar + " WARNING START OF SECTION AUTOGENERATED BY PYTHON SCRIPT\n"
	out += commentChar + " THIS SECTION MAY BE AUTOMATICALLY CHANGED AT ANY TIME\n"
	out += commentChar + " Autogenerated section name: " + sectionName + "\n"
	out += commentChar + " File path of script: ARD/" + filePath.split("/ARD/")[-1] + "\n"
	return out

def autogenWarnEnd(sectionName, filePath, commentChar="%"):
	out = commentChar + " WARNING END OF SECTION AUTOGENERATED BY PYTHON SCRIPT\n"
	out += commentChar + " THIS SECTION MAY BE AUTOMATICALLY CHANGED AT ANY TIME\n"
	out += commentChar + " Autogenerated section name: " + sectionName + "\n"
	out += commentChar + " File path of script: ARD/" + filePath.split("/ARD/")[-1] + "\n"
	return out

def usage(fileName):
	pass

def error(message):
	print(FAIL + "Error: " + ENDC + message)
	print("Halting execution")
	exit(-1)

def warning(message):
	print(WARNING + "Warning: " + ENDC + message)