
.PHONY: all

all:
	python3 genARD.py

headers:
	python3 genARD.py --headers-only

clean:
	-rm -R tex/ memory/ ARD.pdf *.aux *.lof *.log *.lot *.fls *.out *.toc *.fmt *.fot *.cb *.cb2 .*.lb *.synctex.gz
	